### ISSUE TITLE
The image / content is misleading 

### ISSUE THREAD

**Issue by lyrixx** [ishandeveloper/github-wrapped#7]
Many people thought numbers are only for 2020, but it's for ALL history since the code does not use date filtering.

IMHO, the content should be update to reflect the reality of the code

**Comment by ishandeveloper** [comment]
Hey @lyrixx ! Thanks for creating this issue and yes, I totally agree with you. The '2020' there was mentioned as by default github api only sends the data for commits that predate an year from the present day. 

I was initially planning to use createdAt parameter to filter out the data for this year, but the graphql api only allows limits for upto 100 nodes, and in case the number of pull requests/issues exceed let's assume 400 for example, it'd just become too expensive and we'll soon run out of 5000 points per her limit that github allows.

I already have found a workaround that uses the github search rest API [here](https://docs.github.com/en/free-pro-team@latest/rest/reference/search). But, that'd increase the number of requests we'll need to make per user.

I'm currently trying to find some other workaround, that takes advantage of the graphql api. But, if I'm not able to I'll just switch to using the rest API, which could lead to around 3 requests/user, to counter that I'll just add a multiple Token system, so that we can increase the rate limits.

In case anyone you or anyone else have any other workaround/suggestions in mind. Please let me know. 

Happy Holidays! 🎊

**Comment by ishandeveloper** [comment]
@lyrixx I've linked a PR #8 this should resolve the above issue 😄

You can close this issue, if you're okay with the solution : )

**Comment by hugovk** [comment]
Looks like https://github.com/ishandeveloper/github-wrapped/pull/8 was reverted in https://github.com/ishandeveloper/github-wrapped/pull/9.

**Comment by ishandeveloper** [comment]
Thanks for creating the issue.
### Fixed in #16

**Comment by lyrixx** [comment]
Stats looks really strange [to me](https://githubwrapped.tech/lyrixx)
How can I have only 383 commits for 1.1K PR? I'm pretty sure I did not open 1.1K in 2020
This is the number I get from the github UI (this incluces private repo too): 
![image](https://user-images.githubusercontent.com/408368/103344478-00417280-4a8f-11eb-8716-872db5ac192b.png)

**Comment by hugovk** [comment]
https://githubwrapped.tech/lyrixx now shows 121 PRs just like https://github.com/search?q=is%3Apr+author%3Alyrixx+created%3A%3E%3D2020-01-01

**Comment by lyrixx** [comment]
Oh, thanks. I suppose I had some cache. Newbee error, my bad! Sorry for the noise :)
